//autogenerated using vex code Pro V5/*vex-vision-config:begin*/
//#include "vex.h"
using namespace vex;

extern vex::vision::signature BLUE_BALL;
extern vex::vision::signature SIG_2;
extern vex::vision::signature SIG_3;
extern vex::vision::signature SIG_4;
extern vex::vision::signature SIG_5;
extern vex::vision::signature SIG_6;
extern vex::vision::signature SIG_7;
extern vex::vision Vision;
/*vex-vision-config:end*/